"""Create cards table

Revision ID: 4555fba3f85a
Revises: 57a756aa4e5a
Create Date: 2024-03-01 13:09:03.869597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4555fba3f85a'
down_revision = '57a756aa4e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_attempts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('delivery_attempts')

    # ### end Alembic commands ###
